version: '3'
services:
  
  #PHP Service
  app:
    build: ./php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - './app:/var/www'
    working_dir: /var/www
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: skillboxdb
      MYSQL_ROOT_PASSWORD: test_pass
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge